### ISSUE TITLE
Unit tests are running against an EoL version of Ansible-Core

### ISSUE THREAD

**Issue by tremble** [ansible/ansible-zuul-jobs#1704]
the base unit test jobs are explicitly using stable-2.11 - for example:

```
- job:
    name: ansible-test-units-base-python37
    parent: ansible-test-units-base
    nodeset: controller-node
    abstract: true
    required-projects:
      - name: github.com/ansible/ansible
        override-checkout: stable-2.11
    vars:
      ansible_test_python: 3.7 
```

stable-2.11's no longer supported, with the last release being 6 months ago.
